// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khqodjmmdijonptpvfry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtocW9kam1tZGlqb25wdHB2ZnJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTUwMDgsImV4cCI6MjA3NDUzMTAwOH0.lnJ0HdsB2U9Z0jvK0CnU_U8FoIk9sm1uCUEIDLDQt9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});